### ISSUE TITLE
"Sample fixed points..."

### ISSUE THREAD

**Issue by chifman** [knappa/steadycellphenotype#10]
Sample fixed points and cycles does not work. Just hangs in there without returning anything. Tried the simplest model: x1=x2, x2=x1. It has been 5 min ... and nothing.
I think something happened after our last updates. 
Other features appear to work as before.

**Comment by knappa** [comment]
This was a bug which only showed when the size of the model was small and the number of processors was large, leading to empty queues which never get cleared. FIXED
